### ISSUE TITLE
Would you please upload a release prebuild package?

### ISSUE THREAD

**Issue by zhblue** [morphinejh/dosboxece-opl#1]
It's really hard to build all the dependences from scratch.

**Comment by morphinejh** [comment]
You are correct, there are a lot of dependencies. Please get the DosboxECE sources compiling first from [Yesterlay](https://yesterplay.net/dosboxece/). Once you have that working check back and we can figure out the issues. I don't want to post the binaries because it can create more issues. Building from scratch ensure you have everything you need.

**Comment by zhblue** [comment]
Thank you for your fast reply and great works on this project.
I believe that I'm not the only one wish to use opl2xxx things on modem PCs.

**Comment by morphinejh** [comment]
I've added it as an enhancement. I will hopefully have time to get to it. I've only used/tested it on x86-64 systems. I'd also like to try this on a Raspberry Pi when I get the time.

**Comment by zhblue** [comment]
looking forward to it

**Comment by morphinejh** [comment]
Okay, I added 3 binary releases with the source code. No need to compile the *`libmt32emu`* library; I linked it statically. Just make sure all the other libraries are installed before running it. The should be easily installed with `sudo apt install`. Let me know if you have issues.

Performance isn't great on the Rpi's but its playable for 386 games at least.

**Comment by zhblue** [comment]
it has run on my Ubuntu 20.04 with ` sudo apt-get install libfluidsynth2`
but my opl2lpt won't make any sound.
`chmod 777 /dev/parport0` help dosbox overcome the segment fault after privilege complaint.
still no sound.
```
[sblaster]
sbtype      = sb16
sbbase      = 220
irq         = 7
dma         = 1
hdma        = 5
sbmixer     = true
oplmode     = opl2
oplemu      = opl2lpt
oplport     = parport0
oplbaudrate = 115200
oplrate     = 44100
fmstrength  = 150


```

**Comment by morphinejh** [comment]
A few questions:
1) Did you add your user the the "lp" group? That is the group for the printer port.
2) Did you install "libieee1284"?
3) What is the message dosbox is outputting? Make sure you run from the command line and paste the output here of what that says.

**Comment by morphinejh** [comment]
Glad to hear. Please open a new issue for any audio issues you may have. I developed this with only an OPL3LPT, which requires less delay between writes.

**Comment by zhblue** [comment]
![2021-10-07 11-16-17屏幕截图](https://user-images.githubusercontent.com/3926566/136314966-5b47660e-0696-45e3-ac2c-9b98a8633659.png)

**Comment by morphinejh** [comment]
Looks like OPL2LPT is working.

Side Note: Fluidsynth for whatever reason tries to connect to `jackd` audio. Try switching the configuration for it in the `[midi` section to:
```
fluid.driver            = pulseaudio
```

**OR**

```
fluid.driver            = alsa
```
