### ISSUE TITLE
OPL2LPT clone sounds crappy

### ISSUE THREAD

**Issue by zhblue** [morphinejh/dosboxece-opl#3]
Ubuntu20.04 
recent release
maybe remove the delay when dosbox.conf specified opl2lpt as oplemu can help.
[doom-opl2lpt.zip](https://github.com/morphinejh/dosboxece-opl/files/7298476/doom-opl2lpt.zip)

**Comment by morphinejh** [comment]
Thanks for the update. Already working on a fix. Current code relied on usleep() and it is very inaccurate after testing.

Would you be able to test a quick fix version and let me know if it works within the next few hours?

**Comment by zhblue** [comment]
I'll keep my test machine ON !

**Comment by zhblue** [comment]
Perfect !
Both works as fine as on my 486 machine !
