### ISSUE TITLE
I get this open source hardware should works fine with this one.

### ISSUE THREAD

**Issue by zhblue** [morphinejh/dosboxece-opl#4]
https://github.com/zhblue/OPL3USB

convert opl2lpt/opl3lpt to OPL Duo

**Comment by morphinejh** [comment]
Have you been able to test it (as an OPL3Duo!) using DosboxECE-OPL?

**Comment by zhblue** [comment]
not yet, it works fine with Dosbox-X on a bread board, and the new PCB is coming on the way.

**Comment by morphinejh** [comment]
I'm curious if you have any updates on this?

**Comment by zhblue** [comment]
dosbox-x takes too much CPU and sometimes slow down, so I worked further on my own player .
https://github.com/zhblue/OPL3USB/blob/main/vgmplay2usb/WinForm.exe
